<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $beverages = Category::where('name', 'Beverages')->first();
        $snacks = Category::where('name', 'Snacks')->first();
        $canned = Category::where('name', 'Canned Goods')->first();
        $frozen = Category::where('name', 'Frozen Foods')->first();
        $household = Category::where('name', 'Household Products')->first();

        $supplier1 = Supplier::where('name', 'Pacific Beverages Inc.')->first();
        $supplier2 = Supplier::where('name', 'Golden Snacks Trading')->first();
        $supplier3 = Supplier::where('name', 'Metro Canned Goods Corp.')->first();
        $supplier4 = Supplier::where('name', 'Arctic Frozen Foods Co.')->first();
        $supplier5 = Supplier::where('name', 'CleanHome Distributors')->first();

        $products = [
            // Beverages (7 products)
            [
                'name' => 'Coca-Cola 330ml',
                'description' => 'Classic Coca-Cola carbonated soft drink in a 330ml can',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-COLA330',
                'barcode' => '5449000000996',
                'unit_price' => 35.00,
                'current_stock' => 150,
                'low_stock_threshold' => 20,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Sprite 330ml',
                'description' => 'Lemon-lime flavored carbonated drink in a 330ml can',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-SPRT330',
                'barcode' => '5449000001061',
                'unit_price' => 35.00,
                'current_stock' => 120,
                'low_stock_threshold' => 20,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Nestea Lemon Iced Tea 500ml',
                'description' => 'Refreshing lemon-flavored iced tea beverage',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-NESTEA500',
                'barcode' => '4800361414142',
                'unit_price' => 30.00,
                'current_stock' => 80,
                'low_stock_threshold' => 15,
                'unit' => 'bottle',
                'is_active' => true,
            ],
            [
                'name' => 'Aquafina Purified Water 1L',
                'description' => 'Pure and refreshing purified drinking water',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-AQUA1L',
                'barcode' => '0012000001086',
                'unit_price' => 25.00,
                'current_stock' => 200,
                'low_stock_threshold' => 30,
                'unit' => 'bottle',
                'is_active' => true,
            ],
            [
                'name' => 'Red Bull Energy Drink 250ml',
                'description' => 'Energy drink with taurine and caffeine',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-REDB250',
                'barcode' => '9002490100070',
                'unit_price' => 65.00,
                'current_stock' => 60,
                'low_stock_threshold' => 10,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Kopiko 78°C Coffee 240ml',
                'description' => 'Ready-to-drink smooth coffee beverage',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-KOP240',
                'barcode' => '8886001400023',
                'unit_price' => 28.00,
                'current_stock' => 8,
                'low_stock_threshold' => 10,
                'unit' => 'bottle',
                'is_active' => true,
            ],
            [
                'name' => 'Minute Maid Orange Juice 1L',
                'description' => 'Fresh-tasting orange juice from concentrate',
                'category_id' => $beverages->id,
                'supplier_id' => $supplier1->id,
                'sku' => 'BEV-MMOJ1L',
                'barcode' => '5449000134127',
                'unit_price' => 85.00,
                'current_stock' => 40,
                'low_stock_threshold' => 10,
                'unit' => 'carton',
                'is_active' => true,
            ],
            // Snacks (7 products)
            [
                'name' => 'Lay\'s Classic Potato Chips 184g',
                'description' => 'Crispy classic salted potato chips',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-LAYS184',
                'barcode' => '0028400064545',
                'unit_price' => 89.00,
                'current_stock' => 45,
                'low_stock_threshold' => 10,
                'unit' => 'bag',
                'is_active' => true,
            ],
            [
                'name' => 'Pringles Original 107g',
                'description' => 'Stackable original flavor potato crisps',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-PRNG107',
                'barcode' => '5053990101573',
                'unit_price' => 99.00,
                'current_stock' => 35,
                'low_stock_threshold' => 8,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Oreo Original Cookies 133g',
                'description' => 'Chocolate sandwich cookies with vanilla cream filling',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-OREO133',
                'barcode' => '7622210100610',
                'unit_price' => 45.00,
                'current_stock' => 70,
                'low_stock_threshold' => 12,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'name' => 'SkyFlakes Crackers 250g',
                'description' => 'Light and crispy saltine crackers',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-SKYF250',
                'barcode' => '4800092160325',
                'unit_price' => 52.00,
                'current_stock' => 90,
                'low_stock_threshold' => 15,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'name' => 'Planters Mixed Nuts 292g',
                'description' => 'Premium mix of peanuts, cashews, almonds, and pecans',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-PLAN292',
                'barcode' => '0029000016811',
                'unit_price' => 320.00,
                'current_stock' => 5,
                'low_stock_threshold' => 8,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Jack \'n Jill Chippy 110g',
                'description' => 'Corn chips with barbecue flavor',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-CHIP110',
                'barcode' => '4800016551109',
                'unit_price' => 32.00,
                'current_stock' => 100,
                'low_stock_threshold' => 15,
                'unit' => 'bag',
                'is_active' => true,
            ],
            [
                'name' => 'Monde Butter Cookies 400g',
                'description' => 'Assorted butter cookies in a decorative tin',
                'category_id' => $snacks->id,
                'supplier_id' => $supplier2->id,
                'sku' => 'SNK-MOND400',
                'barcode' => '4800166601012',
                'unit_price' => 150.00,
                'current_stock' => 25,
                'low_stock_threshold' => 5,
                'unit' => 'tin',
                'is_active' => true,
            ],
            // Canned Goods (6 products)
            [
                'name' => 'Century Tuna Flakes in Oil 180g',
                'description' => 'Premium tuna flakes packed in vegetable oil',
                'category_id' => $canned->id,
                'supplier_id' => $supplier3->id,
                'sku' => 'CAN-TUNA180',
                'barcode' => '4800092130168',
                'unit_price' => 42.00,
                'current_stock' => 100,
                'low_stock_threshold' => 20,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Argentina Corned Beef 260g',
                'description' => 'Classic corned beef in a convenient can',
                'category_id' => $canned->id,
                'supplier_id' => $supplier3->id,
                'sku' => 'CAN-CORN260',
                'barcode' => '4800036760260',
                'unit_price' => 68.00,
                'current_stock' => 75,
                'low_stock_threshold' => 15,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Del Monte Pineapple Chunks 432g',
                'description' => 'Sweet pineapple chunks in light syrup',
                'category_id' => $canned->id,
                'supplier_id' => $supplier3->id,
                'sku' => 'CAN-PINE432',
                'barcode' => '0024000163268',
                'unit_price' => 55.00,
                'current_stock' => 60,
                'low_stock_threshold' => 12,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Campbell\'s Cream of Mushroom Soup 298g',
                'description' => 'Rich and creamy condensed mushroom soup',
                'category_id' => $canned->id,
                'supplier_id' => $supplier3->id,
                'sku' => 'CAN-CAMP298',
                'barcode' => '0051000012517',
                'unit_price' => 95.00,
                'current_stock' => 7,
                'low_stock_threshold' => 10,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Hunt\'s Pork and Beans 230g',
                'description' => 'Savory pork and beans in tomato sauce',
                'category_id' => $canned->id,
                'supplier_id' => $supplier3->id,
                'sku' => 'CAN-HUNT230',
                'barcode' => '0027000379073',
                'unit_price' => 28.00,
                'current_stock' => 110,
                'low_stock_threshold' => 20,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Spam Classic Luncheon Meat 340g',
                'description' => 'Classic fully cooked luncheon meat',
                'category_id' => $canned->id,
                'supplier_id' => $supplier3->id,
                'sku' => 'CAN-SPAM340',
                'barcode' => '0037600108003',
                'unit_price' => 185.00,
                'current_stock' => 30,
                'low_stock_threshold' => 8,
                'unit' => 'can',
                'is_active' => true,
            ],
            // Frozen Foods (5 products)
            [
                'name' => 'Magnolia Ice Cream Vanilla 750ml',
                'description' => 'Rich and creamy classic vanilla ice cream',
                'category_id' => $frozen->id,
                'supplier_id' => $supplier4->id,
                'sku' => 'FRZ-ICVN750',
                'barcode' => '4800787100758',
                'unit_price' => 180.00,
                'current_stock' => 25,
                'low_stock_threshold' => 5,
                'unit' => 'tub',
                'is_active' => true,
            ],
            [
                'name' => 'McCain French Fries 750g',
                'description' => 'Premium golden crispy French fries',
                'category_id' => $frozen->id,
                'supplier_id' => $supplier4->id,
                'sku' => 'FRZ-FRIE750',
                'barcode' => '8710438091038',
                'unit_price' => 145.00,
                'current_stock' => 35,
                'low_stock_threshold' => 8,
                'unit' => 'bag',
                'is_active' => true,
            ],
            [
                'name' => 'Bibigo Chicken Dumplings 500g',
                'description' => 'Korean-style chicken and vegetable dumplings',
                'category_id' => $frozen->id,
                'supplier_id' => $supplier4->id,
                'sku' => 'FRZ-DUMP500',
                'barcode' => '8801007057477',
                'unit_price' => 210.00,
                'current_stock' => 18,
                'low_stock_threshold' => 5,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'name' => 'Green Giant Mixed Vegetables 450g',
                'description' => 'Frozen mix of corn, peas, carrots, and green beans',
                'category_id' => $frozen->id,
                'supplier_id' => $supplier4->id,
                'sku' => 'FRZ-VEGM450',
                'barcode' => '0020000121024',
                'unit_price' => 120.00,
                'current_stock' => 22,
                'low_stock_threshold' => 5,
                'unit' => 'bag',
                'is_active' => true,
            ],
            [
                'name' => 'Tender Juicy Hotdog 1kg',
                'description' => 'Classic pork and chicken hotdogs',
                'category_id' => $frozen->id,
                'supplier_id' => $supplier4->id,
                'sku' => 'FRZ-HOTD1KG',
                'barcode' => '4800092162022',
                'unit_price' => 165.00,
                'current_stock' => 40,
                'low_stock_threshold' => 10,
                'unit' => 'pack',
                'is_active' => true,
            ],
            // Household Products (5 products)
            [
                'name' => 'Joy Dishwashing Liquid Lemon 500ml',
                'description' => 'Powerful grease-cutting dishwashing liquid',
                'category_id' => $household->id,
                'supplier_id' => $supplier5->id,
                'sku' => 'HH-JOY500',
                'barcode' => '4902430890922',
                'unit_price' => 78.00,
                'current_stock' => 55,
                'low_stock_threshold' => 10,
                'unit' => 'bottle',
                'is_active' => true,
            ],
            [
                'name' => 'Ariel Powder Detergent 1kg',
                'description' => 'Premium laundry detergent powder with stain removal',
                'category_id' => $household->id,
                'supplier_id' => $supplier5->id,
                'sku' => 'HH-ARIEL1KG',
                'barcode' => '4902430890939',
                'unit_price' => 145.00,
                'current_stock' => 40,
                'low_stock_threshold' => 8,
                'unit' => 'pack',
                'is_active' => true,
            ],
            [
                'name' => 'Lysol Disinfectant Spray 340g',
                'description' => 'Kills 99.9% of viruses and bacteria on surfaces',
                'category_id' => $household->id,
                'supplier_id' => $supplier5->id,
                'sku' => 'HH-LYSOL340',
                'barcode' => '0019200044284',
                'unit_price' => 295.00,
                'current_stock' => 3,
                'low_stock_threshold' => 5,
                'unit' => 'can',
                'is_active' => true,
            ],
            [
                'name' => 'Bounty Paper Towels 2-Ply',
                'description' => 'Absorbent and strong 2-ply paper towels',
                'category_id' => $household->id,
                'supplier_id' => $supplier5->id,
                'sku' => 'HH-BOUNT2P',
                'barcode' => '0037000744849',
                'unit_price' => 120.00,
                'current_stock' => 50,
                'low_stock_threshold' => 10,
                'unit' => 'roll',
                'is_active' => true,
            ],
            [
                'name' => 'Glad Trash Bags 30 Gallon 25ct',
                'description' => 'Heavy-duty drawstring trash bags',
                'category_id' => $household->id,
                'supplier_id' => $supplier5->id,
                'sku' => 'HH-GLAD30G',
                'barcode' => '0012587700211',
                'unit_price' => 185.00,
                'current_stock' => 20,
                'low_stock_threshold' => 5,
                'unit' => 'box',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['sku' => $product['sku']], $product);
        }
    }
}
