@extends('layouts.admin')

@section('title', 'Low Stock Report')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="fw-bold mb-0 text-danger"><i class="bi bi-exclamation-triangle-fill me-2"></i> Low Stock Report</h2>
    <div class="d-flex gap-2">
        <button class="btn btn-outline-danger rounded-pill px-4" onclick="window.print()">
            <i class="bi bi-printer me-2"></i> Print Report
        </button>
        <a href="{{ route('admin.reports.index') }}" class="btn btn-outline-secondary rounded-pill px-4">
            <i class="bi bi-arrow-left me-2"></i> Back
        </a>
    </div>
</div>

<div class="glass-card">
    <div class="p-4 border-bottom d-flex justify-content-between align-items-center bg-white d-none d-print-flex">
        <div>
            <h4 class="mb-0 fw-bold">Grocery System</h4>
            <p class="text-muted mb-0">Low Stock Required Action Report</p>
        </div>
        <div class="text-end">
            <p class="mb-0 fw-semibold">Date: {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
            <p class="text-muted mb-0 small">Generated by: {{ auth()->user()->name ?? 'Admin' }}</p>
        </div>
    </div>
    
    <div class="p-0">
        <div class="table-responsive">
            <table class="table table-custom mb-0">
                <thead>
                    <tr class="table-light">
                        <th width="25%">Product</th>
                        <th width="15%">Supplier</th>
                        <th width="15%" class="text-center">Current Stock</th>
                        <th width="15%" class="text-center">Min Threshold</th>
                        <th width="15%" class="text-center">Deficit</th>
                        <th width="15%" class="text-center d-print-none">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($products ?? [] as $product)
                    @php
                        $isOut = $product->current_stock == 0;
                        $deficit = $product->low_stock_threshold - $product->current_stock;
                    @endphp
                    <tr>
                        <td>
                            <div class="fw-semibold text-dark">{{ $product->name }}</div>
                            <div class="small text-muted">SKU: {{ $product->sku }}</div>
                        </td>
                        <td>
                            <div class="fw-medium">{{ $product->supplier->name ?? 'None' }}</div>
                            <div class="small text-muted">{{ $product->supplier->phone ?? '' }}</div>
                        </td>
                        <td class="text-center">
                            <span class="fw-bold fs-5 {{ $isOut ? 'text-danger' : 'text-warning text-dark' }}">
                                {{ $product->current_stock }}
                            </span>
                        </td>
                        <td class="text-center text-muted">{{ $product->low_stock_threshold }}</td>
                        <td class="text-center">
                            <span class="text-danger fw-bold fs-5">{{ $deficit > 0 ? $deficit : 0 }}</span>
                        </td>
                        <td class="text-center d-print-none">
                            <a href="{{ route('admin.stock-entries.create', ['supplier_id' => $product->supplier_id]) }}" class="btn btn-sm btn-outline-primary">
                                Restock
                            </a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" class="text-center py-5">
                            <h5 class="text-success mb-0"><i class="bi bi-check-circle-fill me-2"></i> No products are currently low on stock.</h5>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
